opengovsg/letters

- .github/workflows/ci.yml
Names for ECS and Code Deploy in `ci.yml` for prod appear to be incorrectly labelled as `stg`, changing them to `prod`
> build: fix naming for ecs and codedeploy on prod

- frontend/src/app/AppRouter.tsx
- frontend/src/app/routes/public.routes.tsx
- frontend/src/constants/routes.ts
- frontend/src/features/public/LetterPublicPage.tsx
_Why does this PR exist? What problem are you trying to solve? What issue does this close?_
Closes [this](https://www.notion.so/opengov/Refactor-public-frontend-routes-c4b0bd8a6cb74757a39f7da311a2cae7?pvs=4)
Default `/` will now be the public view instead of `public`
**Features**:
- Refactored the structure of routes 
**AFTER**:
Landing Page:
Public Letters View:
> Chore: refactor routes

- ecs-task-definition.json
OTP logins on [prod](https://letters.beta.gov.sg) currently don't work, because the env variable for Postman API key is not defined
Add the env variable for the Postman API key to the ECS task definition.
After this change, add `letters-<stg/prod>-postman-api-key` to the parameter store and ECS instances will be able to read it as the env var `POSTMANGOVSG_API_KEY`
> build: add postman api key to ecs task definition

- shared/src/dtos/create-template.dto.ts
- shared/src/dtos/templates.dto.ts
Currently requests made to creation of template have to use arrays in a weird way (storing the actual array as a string). Ideally we want to use the native array type for this instead of storing it as a literal string
Change the class-validation
**BEFORE**:
Before change
**AFTER**:
After change
> fix: change class validation

- frontend/src/features/tinymce/components/Editor.tsx
Removes whitespace padding around rendered letter
**Before**
**After**
> fix: remove padding around rendered letter

- frontend/src/app/App.tsx
- frontend/src/app/AppBanner.tsx
To inform users that Letters is still a beta product
> feat: added beta project app banner

- ecs-task-definition.json
- Add otp secret to `ecs-task-definition.json`
> chore: add otp secret to ecs-task-definition

- shared/src/constants/letters.ts
Increase `BULK_MAX_ROW_LENGTH` from 10 to 500
> chore: fix max bulk creation numbers

- backend/src/letters/letters-validation.service.ts
Fixes check for `BULK_MAX_ROW_LENGTH`
If our `BULK_MAX_ROW_LENGTH` is 500, we should allow for the creation of 500 letters, not 499, so we should use the `>` check not `>=`.
Tested on staging, load-wise we are able to handle creation of 500 links. Max CPU utilization in cluster went from 5% to 9%,  but average utilization in cluster remained stable around 2%. No notable spikes in DB usage.
> chore: fix max bulk creation length check

- backend/src/letters/letters-validation.service.ts
- shared/src/dtos/letters.dto.ts
We want to implement the error flow, where users can see the validation errors in the CSV they uploaded
But the validation error types currently reside only in the backend, and so it's not usable by the frontend
Part of [Notion task](https://www.notion.so/opengov/Eng-bulk-creation-error-handling-31e044846ff049f09ed4cfc2f4db0b8a?pvs=4)
Define the validation error types and move them to `/shared`, so that it can be used by the frontend in the future
> refactor: types for bulk letter validation errors

- backend/src/auth/auth.controller.ts
Provide a more helpful error message to the user in case the call to postman fails.
Reusing the error message from go.gov.sg
**Before:**
**After:**
> fix: error message more user friendly when the otp call to postman fails

- frontend/src/features/issue/BulkIssueDrawer.tsx
- frontend/src/features/issue/hooks/templates.hooks.ts
- frontend/src/features/issue/hooks/useParseCsv.tsx
We want to show useful errors to the user when there are issues with their uploaded CSV (when issuing bulk letters)
Closes [Notion task](https://www.notion.so/opengov/Eng-bulk-creation-error-handling-31e044846ff049f09ed4cfc2f4db0b8a?pvs=4)
Show "N errors detected" if there are errors with the uploaded CSV, and show a table containing all the rows in the uploaded CSV with errors.
Added two new frontend states to the drawer:
- `uploadCsvErrors`: stores the response errors, which corresponds to errors in the uploaded CSV
- `isShowUploadCsvErrors`: boolean that controls whether we display the main form view, or the upload csv error view (table view)
- this boolean approach might not be the best, we'll need to refactor it once we add in the final step of downloading the generated csv
**Bugs …
> feat: show upload csv errors on bulk issue drawer

- backend/src/core/dto-mappers/letter.dto-mapper.ts
- backend/src/letters/letters.controller.ts
- frontend/src/features/issue/BulkIssueDrawer.tsx
- frontend/src/features/issue/hooks/templates.hooks.ts
- shared/src/dtos/letters.dto.ts
Previously no link was returned to the user.
The bulk creation response now contains the public id of the letters.
This is used to construct the letters link on the front end before including it in the csv that the admin can download.
- Rename `GetBulkLettersDto` to `GetBulkLetterDto` as that is the correct naming. Thanks Alexis for calling this out.
- Change `createdAt` and `shortlink` in the  CSV to be "Date of Issue" and "Letter Link" to be more user friendly.
**BEFORE**:
**AFTER**:
> Return letter link in csv after bulk creation

- frontend/src/assets/TemplatePreviewFallback.svg
- frontend/src/features/dashboard/components/TemplateCard.tsx
In case the preview image of the template can not be loaded a fallback image gets shown instead.
Closes [Default image for letter template](https://www.notion.so/opengov/Design-Default-image-for-letter-template-766e2ac94dd64058994e6eabb9ebe799?pvs=4)
Using `fallbackSrc` on `Chakra-ui`s `Image`.
In order to achieve the figma design for the fallback image, it was also necessary to update the general card design to match.
**BEFORE**:
**AFTER**:
> Serve fallback image for template preview

- backend/src/config/config.schema.ts
This PR changes "Starter Kit" in the OTP email to "Letters"
> chore: set default otp sender name to letters

- backend/src/core/utils.ts
Increases length of publicId to 32 to make `publicId` more difficult to guess.
> chore: increase publicId length to 32

- frontend/src/lib/monitoring.tsx
We want to connect Datadog RUM with traces
Closes [Notion task](https://www.notion.so/opengov/Eng-Integrate-Datadog-RUM-and-traces-3888e18dc2e447a7a1843a01f7125dbf?pvs=4)
Change `allowedTracingUrls`, in line with these [Datadog docs](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum)
> chore: connect datadog rum and traces

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- e2e/.gitignore
- e2e/README.md
- e2e/fixtures/login.ts
- e2e/global-setup.ts
- e2e/package-lock.json
- e2e/package.json
- e2e/playwright.config.ts
- e2e/tests/login.test.ts
- package.json
This PR sets up E2E tests using Playwright.
This PR took its approach directly from https://github.com/opengovsg/highway/pull/169, which contains more context and details.
To run the E2E tests, run `npm run test:e2e[-headed]` (after running `npm install` in the `e2e/` folder).
E2E tests are currently set up to run on Chromium only.
- Database migrations, if any, are automatically run before running the E2E tests
- If any test fails, the E2E test job in `e2e.yml` uploads its test artifacts to GitHub (useful for debugging)
- It is not necessary for E2E tests to pass for the overall pipeline to pass
**New dependencies** (in E2E folder):
- `playwright` : E2E testing framework
- `cross-fetch`: fetch library for node, used to retrieve emails from maildev running on `localhost:1080`
**New dev …
> test(e2e): setup e2e tests

- frontend/src/features/auth/LoginPage.tsx
- frontend/src/features/auth/components/LoginForm.tsx
Until now the login page had the default starter-kit design.
This PR changes that to be a Letters specific design.
Closes [OTP page login copy](https://www.notion.so/opengov/Eng-OTP-page-login-copy-fedad6d5b8524cabba5110ecda04eddc?pvs=4)
Adopting the layout from Highway.
Using the graphics from the landing page.
**BEFORE**:
**AFTER**:
> LogIn page for Letters

- frontend/src/features/landing/LandingPage.tsx
- frontend/src/features/landing/components/PublicHeader.tsx
This PR updates the two buttons on the LandingPage to point to our OTP login page instead of our Sign Up beta form as the webapp is almost ready for testing. 
**BEFORE**:
**AFTER**:
> chore: update signup buttons to login

- .vscode/tasks.json
- backend/src/core/dto-mappers/letter.dto-mapper.ts
- backend/src/database/entities/batch.entity.ts
- backend/src/database/entities/letter.entity.ts
- backend/src/database/migrations/1686218786357-remove-unused-rawcsv-from-batch.ts
- backend/src/database/migrations/1686221927894-add-is-password-protected-flag-to-letter.ts
- backend/src/letters/letters-encryption.service.ts
- backend/src/letters/letters-sanitization.service.ts
- backend/src/letters/letters-validation.service.spec.ts
- backend/src/letters/letters-validation.service.ts
- backend/src/letters/letters.controller.ts
- backend/src/letters/letters.module.ts
- backend/src/letters/letters.service.spec.ts
- backend/src/letters/letters.service.ts
- frontend/src/features/issue/BulkIssueDrawer/UploadCsvForm.tsx
- frontend/src/features/issue/hooks/useParseCsv.tsx
- package-lock.json
- package.json
- shared/src/dtos/letters.dto.ts
For Letters with sensitive information the users has asked to support password protection of letters, so that the letter can't be read by unauthorised parties.
Additionally to the password protection, this PR also encrypts each of the password protected letters (and the letter parameters) with the individual passwords as keys and does not store these keys so that only the issuing officer (the the recipient with the password) could decrypt the letter in the DB.
Closes [Notion: [Eng] Letter protection w/ password Issuing - Encryption](https://www.notion.so/opengov/Eng-Letter-protection-w-password-Issuing-Encryption-88f6df014b7646b7ba7aa43810f1377f?pvs=4)
Further details: [Notion: Letters Security](https://www.notion.so/opengov/Security-766d574464c94e0ca5c613a6b86f7cfe?pvs=4)
- The officer …
> Password protection (on bulk issueing)

- backend/src/letters/letters.service.spec.ts
- backend/src/templates/templates-parsing.service.ts
- backend/src/templates/templates.controller.spec.ts
- backend/src/templates/templates.controller.ts
- backend/src/templates/templates.module.ts
- backend/src/templates/templates.service.spec.ts
- backend/src/templates/templates.service.ts
- frontend/src/features/create/components/CreateTemplateModal.tsx
- frontend/tsconfig.json
- shared/src/constants/regex.ts
- shared/src/util/__tests__/templates.spec.ts
- shared/src/util/templates.ts
When creating a new template, repeated fields (enclosed in double curly brackets) are added as new unique fields
- Added shared
- `TEMPLATE_KEYWORD_REGEX` to identify keywords in templates
- `normalizeFields` to deduplicate and set fields to lowercase
- `normalizeHtmlKeywords` to convert keywords in html to lowercase
- Frontend
- Added logic to handle deduplicate and convert fields to lowercase inside the `getFields` function of `CreateTemplateModal`
- Backend
- Added `processTemplate` function in `templates-parsing.service.ts` to store param cleaning and html parsing function
- Updated `templates.service.ts` to call `processTemplate` before creating a new template
> fix: duplicate and case insensitive fields in template creation

- frontend/src/features/dashboard/TemplatesPage.tsx
- frontend/src/features/dashboard/components/TemplateCard.tsx
- frontend/src/features/dashboard/components/TemplatesBody.tsx
- The zoom animation of the template card was broken as that card was cut off on any side of the parent container when zoomed in
- Th shadow on any side touching the parent container was cut off.
- The top border radius of the card was not correct.
This PR fixes these issues.
**BEFORE**:
**AFTER**:
> fix: fix zoom on hover and border radius of template card

- frontend/src/features/public/components/PasswordProtectedView.tsx
Upon entering a password for password protected letters the component would re-render. This was causing focus issues on mobile keyboards.
This PR fixes that behaviour, to only update the input field value instead.
Moving child components out of the component function to the top level of the file.
See issue and solution [here](https://stackoverflow.com/questions/42573017/in-react-es6-why-does-the-input-field-lose-focus-after-typing-a-character)
**BEFORE**:
https://github.com/opengovsg/letters/assets/12240377/3c3fc9f7-d331-440c-a585-55cedd25ef17
**AFTER**:
https://github.com/opengovsg/letters/assets/12240377/0b97e282-7f1d-439a-a0e5-705cca22170a
> fix: do not rerender when password is entered

- backend/Letters.postman_collection.json
- backend/src/letters/letters.service.spec.ts
- backend/src/templates/templates-parsing.service.spec.ts
- backend/src/templates/templates-parsing.service.ts
- backend/src/templates/templates-sanitization.service.ts
- backend/src/templates/templates.controller.spec.ts
- backend/src/templates/templates.controller.ts
- backend/src/templates/templates.module.ts
- backend/src/templates/templates.service.spec.ts
- backend/src/templates/templates.service.ts
- frontend/src/features/create/CreateTemplatePage.tsx
- frontend/src/features/create/components/CreateTemplateModal.tsx
- frontend/src/features/editor/components/TemplateEditor.tsx
- shared/src/constants/regex.ts
- shared/src/dtos/templates.dto.ts
- shared/src/util/__tests__/templates.spec.ts
- shared/src/util/templates.ts
This PR handles the different instances of valid and invalid keywords when creating a new template and adds dynamic highlighting of keywords into the editor to whenever a user defines a keyword, as well as implementing the relevant field and html validations during backend template creation.
Closes [Template variable handling](https://www.notion.so/opengov/2ccadbea5c734aa09614b4ca8cc7177e?v=76cff9fca57b496f857c990e2639af2f&p=a0c8c5b621304863ae40a7be09acfa11&pm=s)
- Shared
- Updated constant `TEMPLATE_KEYWORD_REGEX` to match against keywords with two or more braces, containing lowercase alphanumerics and underscore only
- Added constant `TEMPLATE_KEYWORD_CHAR_REGEX` to accept only lowercase alphanumerics and underscore keywords
- Added constant `TEMPLATE_KEYWORD_DELIMITER_REGEX` to match …
> feat: create template variable handling

- backend/src/config/config.schema.ts
- backend/src/core/dto-mappers/letter.dto-mapper.ts
- backend/src/database/entities/letter.entity.ts
- backend/src/database/migrations/1687250665550-add-first-read-at-column-to-letter.ts
- backend/src/letters/letters.service.ts
- backend/src/public/public.controller.ts
- frontend/src/features/dashboard/IssuedLettersPage.tsx
- frontend/src/features/dashboard/components/IssuedLetterDrawer.tsx
- shared/src/dtos/letters.dto.ts
_Why does this PR exist? What problem are you trying to solve? What issue does this close?_
This PR adds the read receipts feature for letters after they are issued. Whenever the link is accessed, the read receipt will be marked as read, both in the table of issued letters and the additional information displayed in the drawer.  
Closes [add read receipts](https://www.notion.so/opengov/2ccadbea5c734aa09614b4ca8cc7177e?v=76cff9fca57b496f857c990e2639af2f&p=4f40e879c1e1428cb301eb5465a25a79&pm=s)
Described in the notion doc above. 
We added a new column in letters table for recording the `firstReadAt` timestamp 
Based on the `firstReadAt` timestamp information we display, whether the letter has been read or not (will be nonnull if the  letter has been read). …
> chore: add read receipts for letters 

- ecs-task-definition.json
We want to increase the default OTP expiration time. As we need to set the value via the Param Store, we need to add it to the `ecs-task-definition.json` file so that the value will be read from Param Store on deployment.
> chore: add OTP_EXPIRY to letters ecs-task-definition

- frontend/src/utils/csvUtils.ts
We are trying to make the CSV uploads flow smoother, by eliminating blank lines from the CSV processing automatically instead of throwing error to the user that there is a blank line missing, which can sometimes be hard for the user to debug since, they are unable to recognise or "see" the missing lines on excel. 
Hence the code change involved here, is to remove the blank lines from CSV and also inform the user the number of blank lines that were ignored while their CSV file was processed.
Closes this [notion task](https://www.notion.so/opengov/Eng-Error-handling-for-CSV-uploads-47eb937d69274a03b4ae551446d16f4c)
Make changes to the `papaparse` config to ignore the empty lines in the CSV.
We have implemented 1 in this PR.
**BEFORE**:
--> error were being …
> fix: remove empty lines from CSV processing

- frontend/package-lock.json
- frontend/package.json
- frontend/src/features/editor/components/LetterQRCode.tsx
- frontend/src/features/editor/components/LetterViewer.tsx
We are adding QR codes to letters, so that anyone can scan them and easily access the the link to the letter. 
Closes [this notion task](https://www.notion.so/opengov/Eng-Dynamic-QR-code-generation-ba96a9971dea42b48005f4f1862b5e46)
We are using `react-qr-code` library for generating QR codes for links to different letters on client side. 
More details on the approach can be found [here](https://www.notion.so/opengov/20230624-QR-Code-Generation-for-Letters-b36e2699faff4a40b72279fb467b4c44)
**Features**:
- QR code will be shown when the letter is viewed and if there's a letter ID that exists. 
- No QR code is shown in preview [that's because we don't have a letter ID, although we can show a sample QR code for just preview purposes if required.]
**BEFORE**:
Letter preview without the QR …
> feat: Add QR Codes to Letters 

- frontend/src/features/issue/BulkIssueDrawer/UploadCsvErrorsTable.tsx
We are trying to improve the design for CSV uploads. In this PR specifically we will group the errors for each row together, so that's it's easier for users to process these errors. 
Closes this notion [task](https://www.notion.so/opengov/Eng-Error-handling-for-CSV-uploads-47eb937d69274a03b4ae551446d16f4c).
Fixed the design. Did some front-end processing to group errors from the same row together using `reduce`.
Since we don't expect a ton of errors anyways (the scale of errors would be limited by the number of letters generated in one go), front-end processing would still make sense and should not be too heavy.
**Features**:
- Group related row errors together
**BEFORE**:
**AFTER**:
https://github.com/opengovsg/letters/assets/25703976/60edb725-85b1-47f3-88e7-2f70a41eca9c
> fix: csv uploads error UI

- frontend/src/features/issue/BulkIssueDrawer/DownloadCsv.tsx
To make the link to the letters clickable, we are appending `https://` in front of the letter links.
Closes [task](https://www.notion.so/opengov/Add-https-in-the-letter-link-in-csv-output-4bd8d9c06fa64e709ee10eaf7111dc96)
Added `https://` in front of the letter link only for CSVs. For the rest, we don't really need to add in the `https://`
**BEFORE**:
**AFTER**:
NOTE: adding `https://` to localhost wouldn't work, hence the link doesn't load in the end.
https://github.com/opengovsg/letters/assets/25703976/b8474039-cc4e-4a4c-b1ab-3ce8000bee8d
> fix: add https for letter link

- frontend/src/features/public/LetterPublicPage.tsx
We are hiding the `Download as .PDF` button for now, since users can still use browser tools for printing the letters, moreover, the pagination of letters still remains a problem. 
Closes [notion task](https://www.notion.so/opengov/Eng-Hide-download-pdf-button-9ffd0cee684444c69d87adaa0645a9f9)
Commented out code for the `Download as .PDF` button
**Bug Fixes**:
- We are hiding the "Download as .PDF" button 
**BEFORE**:
**AFTER**:
https://github.com/opengovsg/letters/assets/25703976/db268808-333a-4de3-a64b-60386446abe4
> fix: hide download button

- frontend/src/features/dashboard/TemplatesPage.tsx
Since user won't be able to create new template anyways, we are changing the button for adding new template to requesting new template and routing them to a form for requesting the creation or addition of a new template.
Closes this notion [task](https://www.notion.so/opengov/Eng-Modify-Add-New-template-button-to-Request-to-add-new-button-f48785454d78461e8d2cebd401f186b6)
1. Change the button to a link and open the form page in a new tab, when the `Request New Template` is clicked. 
**BEFORE**:
**AFTER**:
https://github.com/opengovsg/letters/assets/25703976/13f45621-c891-4b9b-91cc-498ce911fae7
> fix: add template -> request template button

- backend/src/batches/batches.service.ts
- backend/src/letters/letters.service.ts
- backend/src/public/public.controller.ts
- frontend/src/features/public/LetterPublicPage.tsx
- frontend/src/features/public/components/PasswordProtectedView.tsx
- frontend/src/features/public/hooks/letters.hooks.ts
- frontend/src/types/PasswordResponseError.ts
- frontend/src/types/ResponseError.ts
- shared/src/constants/letters.ts
In the previous, we added password instructions flow for the officers, in this PR we are going to be adding the flow for password instructions for citizens and how the password instructions would be shown to them before they actually open and access the letter.
Closes [insert issue #]
- Passing the password instructions as part of the JSON error we pass, when password is required to block the letter.
**Features**:
- Show password instructions entered by the officers while generating the letters to the citizen when they access the letter. 
**BEFORE**:
Enter password screen before: 
**AFTER**:
E2E flow tested here: 
https://github.com/opengovsg/letters/assets/25703976/8989b8dd-3ce6-47f0-85a9-ada449f1f986
When no password instructions are provided:
> chore: [citizen] password instructions

- backend/src/batches/batches.service.ts
- backend/src/database/entities/batch.entity.ts
- backend/src/database/migrations/1688119081079-add-password-instruction-to-batches.ts
- backend/src/database/migrations/1688491822294-add-password-instructions-to-batches.ts
- backend/src/letters/letters-validation.service.spec.ts
- backend/src/letters/letters-validation.service.ts
- backend/src/letters/letters.service.ts
- backend/src/public/public.controller.ts
- frontend/src/features/issue/BulkIssueDrawer/UploadCsvForm.tsx
- frontend/src/features/public/LetterPublicPage.tsx
- frontend/src/features/public/components/PasswordProtectedView.tsx
- frontend/src/features/public/hooks/letters.hooks.ts
- frontend/src/types/PasswordResponseError.ts
- frontend/src/types/ResponseError.ts
- shared/src/constants/letters.ts
- shared/src/dtos/batches.dto.ts
- shared/src/dtos/letters.dto.ts
This PR adds the password instructions flow for officers to input the instructions to unlock a password protected letter. In the future PRs, we'll be completing the citizen flow for how these instructions are displayed. 
Closes [task](https://www.notion.so/opengov/Eng-Officer-side-setting-password-unlock-instructions-for-protected-letter-8f45c77a78cc4e5ba84e7bff79aa6639).
- Allow officers to set password-unlock instructions for password protected letters
- [backend] Modify the batch table to add `passwordInstructions` column  (done)
- [backend] Modify the current `LettersController`, `LettersService` to save the `passwordInstructions`
- [frontend] Update the screen, hooks and forms to add Password Information field (done)
**BEFORE**: …
> chore: [officers] add passwordInstructions flow

- backend/src/core/utils/generate-public-id.spec.ts
- backend/src/core/utils/generate-public-id.ts
- shared/src/constants/protected-namespaces.ts
This PR fixes the letter ID generation algo for generating a more "readable" letter ID. 
Closes this [task](https://www.notion.so/opengov/Eng-Update-letters-UUID-25a9255bb22f4b62b8adb7e8d84a4b91).
1. Make letter ID length `size = GROUPS x BLOCK_SIZE`
2. We first generate the letter ID
3. Then insert the dividers in between using regex expression matching logic. 
**BEFORE && AFTER**:
The screenshot below shows the newly generated letter ID vs the old letter ID [in the second row]
End to end testing video:
https://github.com/opengovsg/letters/assets/25703976/902da2f6-b2c9-4dfc-aec8-79dded042876
> fix: letter id generation

- frontend/src/app/routes/admin.routes.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/constants/routes.ts
- frontend/src/features/create/CreateTemplatePage.tsx
- frontend/src/features/create/components/CreateTemplateModal.tsx
- frontend/src/features/issue/BulkIssueDrawer.tsx
This PR changes the route to template creation from `{host}/admin/create` to `{host}/admin/templates/create`
Closes this [task](https://www.notion.so/opengov/bug-Fix-frontend-route-for-template-creation-to-admin-templates-create-instead-of-admin-create-480231d157024e838e3e821150ad8349)
- Nested the `create` path under `templates` route section in `routes.ts`
- Moved path to template creation page under `templates` route
- Updated routes to template dashboard for components navigating to it
> fix: template creation route

- backend/src/templates/templates-parsing.service.ts
- shared/src/util/templates.ts
This PR fixes the issue where there are cases of leading and trailing whitespaces of template variables not being trimmed as it should be, it was observed that `&nbsp;` characters were not being treated as whitespaces and thus not adhering to the parsing logic during creation.
Closes this [task](https://www.notion.so/opengov/bug-whitespace-trimming-before-and-after-template-variables-not-working-on-variable-validation-e5934f9cfb3642398e30d6cb7bb039b1?pvs=4)
- Added a line to replace all `&nbsp;` characters in the html string with whitespace before parsing in `TemplatesParsingService`
- Removed replacing `&nbsp;` in `parseTemplateField` as there will no longer be instances of `&nbsp;` still existing in the string
**BEFORE**:
https://github.com/opengovsg/letters/assets/119388168/13249785-a8b …
> fix: template variable whitespaces
